### PR TITLE
Log in working

### PR DESCRIPTION
**Pull request by Br3nda**
I added methods straight onto the component (probably a tidier way to do this)

When the login button is pressed, it asks the production server if this is good enough to get a session.
If it fails, we print the message from the server/browser
if it succeeds, it just goes into the debugger for now.

To work, this needs the client_id set on the Login component `attemptLogin` method. 

How do I get variables from the `.env` file?
How do I make it navigate to the dashboard on success?

### CODE REVIEW

**Comment by MeghanHughes** [comment]
How do I get variables from the .env file?
We are using [dotenv](https://www.npmjs.com/package/dotenv) to get access into the .env file. Here's an example from `server.js` (though it's currently commented out)
```  webpush.setVapidDetails(
  'mailto:meghan@manu.net.nz',
  process.env.PUBLIC_VAPID_KEY,
  process.env.PRIVATE_VAPID_KEY
)```

**Comment by MeghanHughes** [comment]
How do I make it navigate to the dashboard on success?
We'll just have to add a ternary and use (Next.js routing through the `<Link>` component)[https://github.com/zeit/next.js/#with-link]. I'll set that up!

**Comment by MeghanHughes** [comment]
Hey @Br3nda pass this onto me to finish off - I just want to check something with our snr dev tomorrow.

**Comment by Br3nda** [comment]
Cool. Just in case you missed it, i sent a valid production client id to you a few weeka ago. It's still good. I can make another if u need.

**Comment by MeghanHughes** [comment]
Tots - I have been using in Postman to make test api calls ;-)

**Comment by MeghanHughes** [comment]
https://www.npmjs.com/package/babel-plugin-inline-dotenv

**Comment by MeghanHughes** [comment]
Ok so I have added a router push to the dashboard on successful login. I will slack the username and password you can use to test it.
unsuccessful login gets a network error.
The client_id which is required for login is stored in the .env file

**Comment by janie-t** [comment]
When login is successful there is visible code just above the login form saying 'setState...'

**Pull request merged**
