### PR TITLE
Feature/api base in config

### PR DESCRIPTION
**Pull request by Br3nda**
Moving the server url to one place, so we can change it easily. 

note i branched from #171 to do this

Once the url is moved to config we'll be able to make the dns changes
so that

api.wharehauora.nz points to the api server
app.wharehauora.nz points to this app

this app needs to be configurable first

### CODE REVIEW

**Comment by Br3nda** [comment]
I've moved the api base to ENV - that means we can set it on each heroku. 
so staging can point to staging API etc.

**Comment by Br3nda** [comment]
@Kamikazilady This PR contains the changes needed to move from hard coded urls to having these in config. it means we can deploy the app over and over to heroku to let you test it.
this proposed change is dpeloyed to https://whare-pr-staging-pr-178.herokuapp.com/

**Comment by Br3nda** [comment]
What is thw error you get?
Does it show immediately? Or after doing something? Is there any loading screen before the "straight to error"?

**Comment by Br3nda** [comment]
@Kamikazilady i can't reproduce the error  - Can you check again that you were on the deployment in this PR? I'd love to get this merged

**Comment by Br3nda** [comment]
Hiria please please send screen shot... I am completely blocked by this.

I really need more info on exactly what error message you got (the message, not just that it was an error) and what you were doing at the time (e.g. I was logging in -- or I was typing my email, or I was trying to load the login page) etc.

**Comment by Kamikazilady** [comment]
Issue fixed

**Comment by Br3nda** [comment]
@Kamikazilady can i get you to approve it? then i can merge

(rather than closing it)

**Comment by Br3nda** [comment]
I'm gonna take @Kamikazilady 's comment as approval, and merge this.

**Pull request merged**
