### PR TITLE
Pin node version to 8.11.1

### PR DESCRIPTION
**Pull request by Br3nda**
Not sure what version you're using -- picked the recent stable version.

### CODE REVIEW

**Comment by Br3nda** [comment]
Pinning the node version caused from packages to want to update -- so i've pushed a package-lock.json too

**Comment by MeghanHughes** [comment]
Cool - I am on v 8 so I will check in with Janie and AM and we'll all upgrade if necessary. So I'll wait till we all confirm we're on v 9.1.1. till I merge this?

**Comment by Br3nda** [comment]
Sweet as. We could pin it to 8 instead if that's easier.

**Comment by MeghanHughes** [comment]
Cool - we all seem to be on 8.0.0. If you're happy with that let's pin it to that.

**Comment by MeghanHughes** [comment]
Sounds good! Will make sure the others know to update ;-)

**Comment by Br3nda** [comment]
@MeghanHughes re-done as 8.11.1

**Pull request merged**
